#Bot token for the chat bridge
Bot-token: NjY3NjQ1OTIyMDQ1NTkxNTUz.XiFvuA.ChjWz9ijv8Oc5Tj8kNKA-9MWyDI
#Channel id for sending player messages and messages for other events to
Channel-ID: 760624272656826398