name: L2X9ChatBridge
version: ${parent.version}
main: org.l2x9.chatbridge.ChatBridge
authors: [ 254n_m, AlexProgrammerDE ]
description: ${parent.description}
website: https://www.l2x9.org/
softdepend:
  - L2X9Core
